apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ksops-smoke
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blobor/homelab-gitops.git
    targetRevision: main
    path: platform/ksops-smoke
  destination:
    server: https://kubernetes.default.svc
    namespace: ksops-smoke
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
