apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.102.4
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/platform/tailscale-operator/values.yaml
    - repoURL: https://github.com/blobor/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/blobor/homelab-gitops.git
      targetRevision: main
      path: platform/tailscale-operator/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged   # proxy pods: NET_ADMIN, privileged sysctl init container
