apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snmp-exporter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      targetRevision: 9.18.1
      helm:
        releaseName: snmp-exporter
        valueFiles:
          - $values/platform/snmp-exporter/values.yaml
    - repoURL: https://github.com/blobor/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/blobor/homelab-gitops.git
      targetRevision: main
      path: platform/snmp-exporter/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
