apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: monitoring
type: Opaque
stringData:
    telegram-token: ENC[AES256_GCM,data:4TjNwLOtUAXg21AQhKk+tZL36rkV8jjVC9DL5Ru4EaO1u+AFz3SJ6Ejs3N7Uxg==,iv:Pda50C0f8+sunXYYWzy2w4RAScJjXsugBknrpTeZMHI=,tag:j4225FtuSDNd8leFQotJ3Q==,type:str]
    healthchecks-url: ENC[AES256_GCM,data:VwkTjyaBMBv158lLNOkMotc+qz9/Eaut1WhqFFlxY8XSFyEXosElmh6Kc9NylMNfDPWlpFSo61U=,iv:GHyTJLsnDOdp7vxzO2gJE2u9RzFSRzgmrokrKGXELUY=,tag:E0OZbSn7stZkt2yaEZ91cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ3BPbkx0WWVZalVQMFE4
            cFhTRDJ2MDh6Z2lJZHBjbGJIQ3ZMUE9XSUhzCkxWV1FmMkd3NXZLeGMxaGUrWHJZ
            VkxLS210cVI3dUFscFNYU1pTVEtSeU0KLS0tIGRlRDhqR2FqemxGQ2dFdU9ROEJT
            Zmd4VWhVSTU0REFGaXFjbW16QXRLSzQKyOI+5gyySLkYhg8WF77sahcrBYfXzo4r
            lR07bNul49yVksSDcoeu7t6m3Leqle+JSzNMBJmwINzaNiGpmwwv9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T08:23:42Z"
    mac: ENC[AES256_GCM,data:Ov3sUzCjLtimwvwjF3sQ4oGqNyObNKU0AnVp9aX40Rotzvo9QLHa8ntV1H88XX9vPXXnxjhwuEeRU61SyHNKa+ZRIy9rieDK/c4MT6KSrgEyvGjzmsl+oakNsvaCjnLeAGZXc0bv/PRozHks9Iw2a3JuA8ZJtSd1BN/l1VzPniA=,iv:91YjPbBoJY0B7sih5+B+zNMcctG380wcNnRYdt84UkQ=,tag:G3RDYlMTkByf6rhhhCyB+Q==,type:str]
    version: 3.13.3
