apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: monitoring-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - alertmanager-secrets.sops.yaml
  - grafana-admin.sops.yaml
  - node-heartbeat.sops.yaml
