apiVersion: ENC[AES256_GCM,data:kjx9ZdHNX18=,iv:q43TuUM5LFiBNXbpU/g3A5eTNBHm/vOZyIVr6poeG1g=,tag:Sl8125BkMyX+bGUmm9a9rA==,type:str]
kind: ENC[AES256_GCM,data:1QLfdGu/YVfp8WDKQooyZJBwmK9Lrw==,iv:WsLoWOqsNo+eQBcFBUCYi1b/OLIF9SUC7dCnRWZyvpI=,tag:Ev3NaI6i7fvU7UHW9ax4xw==,type:str]
name: ENC[AES256_GCM,data:FkS3LSw0N9tO,iv:WvpN6wsCyzlbeCLAEfUeZ9YnBKEAB8ia7gjsi2tuIoU=,tag:8fodxxcRS0Emb0Dv7RfUaQ==,type:str]
environment:
    - ENC[AES256_GCM,data:SW/ka3WK2mTgZioS8iTD6XKSjATZACm4gOs7vBGZ4adP7cezr7pjhnjI5zQDwCEj9MJJvMGt30xWeHpd/hSKAazIo+R9HWPR,iv:onSPDWIUwS+uj3tafD4TAmX0SlST/oSGZUcxjz6XDK0=,tag:EbLN67vUL1v/4l8EJ2NBBA==,type:str]
    - ENC[AES256_GCM,data:odC5cliLdfeTnNsecYMHqP7Fyg==,iv:MC19EsudZ6Ojp7YxRWrhvqBZ0RJnJ4r1PsntcirHwGA=,tag:LdB6Cu21Rf9WUVJjOL9Tfw==,type:str]
    - ENC[AES256_GCM,data:5LL39kCgEB4e7LGy04przjnvkwSZKOdkA2yks7x+FTiG7HHf+Q==,iv:mknH9shGRWrnn06Si7vXrb4jTGs1cnbN1KWpRnudoeU=,tag:JoZ8hbyfsYbGTmp0ShlAVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbFdob0RmY2VKeVhhanZO
            eU5tWDZJUC9CZ3d0S081ZVRUU25lL2lzUG5RCllFMExYRmMyOHVqMngwSm5uTjRJ
            TG5VSCtCL3R6WjYzc3R3RzR3YkxWZEkKLS0tIDVHRjAzMkZCMlpDVkhPWjBJOStP
            SzNzcFdMSmxsWDlZS1NUWTh1d0RNb2sK+u5tE1WlPxLTtVa51fSyoqbw81BMWDVi
            0lNnkwpyljw1iUlNZL82mqRY0eb42+7nQZa5ID/y6UoR4UChfbos4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    lastmodified: "2026-10-06T08:29:30Z"
    mac: ENC[AES256_GCM,data:VPKyv6x+JJpG51qR6wylHnGKeB9Eizylp9khjkO8pURGOj5062FWjoxoqlAI+NeyZpbPmPmF/Z9/ZL2fUGNeqXedyZ0tNtyYiobtslLe0i6Cw7LB8sfGCEXN7mYtgcZzP+QXZAKas6vgBHNFbkCCyZxe5jCWAgn+fShCSMIIl54=,iv:w8jQYNMvaxaE3OFEeqb7wNK9n2g65dUgDkc9A9L4B24=,tag:krihfDSOPLru0IkywcZLoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
