apiVersion: ENC[AES256_GCM,data:Y/YhJk8dAwY=,iv:/NiWM3dRIz1f9OA0k4GbugNNXP3+SPcwrwczgjzKkwU=,tag:JcUQoy/PcfTXiwWIg/dDHQ==,type:str]
kind: ENC[AES256_GCM,data:7p/um1BGqTBYiput5erMz4gxwZdyxQ==,iv:1tjzYCQ9fCoTBHkg3mDTsaYPfg3syXCQTBvGa0c2l0A=,tag:3yspVZCOi3FggsaJMJsUyw==,type:str]
name: ENC[AES256_GCM,data:QJnrf2mQ6bgO,iv:1lzKNqNe4sz+fDEmCVx/ly65oZGlkB/NkUA0KISj9OU=,tag:T0x7y+xfe1s8L+0dM6Sinw==,type:str]
environment:
    - ENC[AES256_GCM,data:cqovV20rElLB8J/OqMQnKkG0lbDgMdWcMG2UGnMc96dq6ToRxH9c7UtUiNRaGIAcmUR/CVwC11y4jV1u70xDcys8XvNkZc84,iv:YVJCL0+iMjuz6yIwJwgNY1aEVCmjnjYtSZ/YwRTzb9o=,tag:SiEFwwL/2/ahfAd/C8rBOQ==,type:str]
    - ENC[AES256_GCM,data:As5OIMdoK1F6TC23Zn4E+5f1Kg==,iv:1VgeiJbF+QsIL1ztYZylE55/bPeceDkFPjZxsc1Xrjw=,tag:xkUJ2QpRrmQuyl8tsq+/Dw==,type:str]
    - ENC[AES256_GCM,data:eCsS7pZ/lCpxy/Gm9bn9tZY7ZR0iDKyZvFkNYqTeS84DeTdgiw==,iv:GAqys7UYyqMuiZGbwY9ETF17QDVm0Fzt3/Zo423j+jg=,tag:bJwecLFwDG/auKsdvBjqNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdllNdEVhdTJUdy91bWxT
            YXNvYlNNd1kvMTdwT1czTXJldEVuTXZLTDNrCkdNRXFjOXZoMlM4ZXBFY1QrMVRM
            ZEYwQUhvT3VER2JaTmk0S3JDc1pBemcKLS0tIE9GdVg1dUhPaGVZM2FkeS9XK1Q2
            Y1RUbUY5TVV6Szhzbm9NSVRIUlNOSUEKlaoAgjv060hyJFai3jjmKEpx1vCfzq56
            F1DOWaqQHCEOobU0OUkJeRJYVvTemlDoHWDRHFuCnVe+XhjKEeoGfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    lastmodified: "2026-10-07T11:22:21Z"
    mac: ENC[AES256_GCM,data:pZeAxXn1XjxjwGBR9Wkx1UzcfEyYaHEML4aSJk9zWUoeYuSQns7m4FsWfa3ERFKWGVHUaZhBnu5fQzukXLsSmmPcMFkm9Nhqwo21NAgr2LavkNpk0xbHZkXR8WRZUKVIVBUvAAMDdT04h8WD8RDKaISSaArjtfT7Yd7f2zapzmo=,iv:r0FplkW8LnhbYJ0Rl6IAh7rzAIJC4+KeblRacBfhGXM=,tag:lnstCKih9Melx989GGZGEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
