apiVersion: ENC[AES256_GCM,data:jpfwvUoE1Bs=,iv:43TgZcBy1SXS6tUJLhRa88FHcSCOkSpcxciNXHYXZeI=,tag:2Pn8MUig3303/KPTli0sdg==,type:str]
kind: ENC[AES256_GCM,data:zAzOG6JBe+uHOSzrxouSRGVQhNCGgA==,iv:YLjJgPLR2scLjUqrE7oAzoqqFH43uTQP5tlM6AEag1U=,tag:hxFUfGEQaROZTM/ctkYfhA==,type:str]
name: ENC[AES256_GCM,data:5KPtQ/76BSi/,iv:hK80QtJDqthXSTDoh6C3UzGjr5HQmTuKSPrOmg9wqxw=,tag:bQzUgqyK6jc8lNEWcyNHYg==,type:str]
environment:
    - ENC[AES256_GCM,data:9dkGInMe6D07dF4AnCj9SUY6tpwAQ6gLLmZ62S43SklY8MUN6SSVbPGTUbO+BfBMJjt9wOTJlpOcp1bivny5iK3nLBJ9khbV,iv:SxtQH+PaIGRi3lTw4mIQFwDyaxL5pGyj2aPbnTiiLB4=,tag:UJJMhydlWfvUNJUyxxWeAA==,type:str]
    - ENC[AES256_GCM,data:0RlStNnLwikChsRyc3tgW4TyaA==,iv:wXKzgEWA+ujU3VpRrXp2nFphCBhSRIQmUWYeOPi5WTo=,tag:MnFVsBlX/Yu74y1BBzmEbw==,type:str]
    - ENC[AES256_GCM,data:kfoEYGRnjyais3PfZZkhR5B/EsVEI0XVJMlBNXohe/nxn0l2qw==,iv:QZrhVO0+YpszJDO892ebqOBqSTXxHmJj1W6ydn03XPY=,tag:7/EYzAzeJYt+2zM42kOE0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSENCY0lJYTJPOVA1ejI0
            TXF6SjFxTWcwZGFLQjFoYUovY1VRTFNHcjBNCmtLc0VSMFdTdlV6dHpROFlZWlJW
            MlFTOXhmNWNTL05MajFYd096Y1Fpc1UKLS0tIFVVcjVEaVRKREJzb3FaV3RMcjlJ
            QlROa3JHcVk5bEtuOG5neElwdTFBcUUKtcULY82GUnDYAjw0StrfFyvka2WIX080
            GX0TIMmokK1hUZyXylZQaOyI+qWYt+RJglCqqal91rdUxCtHmizjYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    lastmodified: "2026-10-07T11:22:21Z"
    mac: ENC[AES256_GCM,data:9G1eo6oGNiAFo93pxGS5sB62tJmSnuwBR5k9KQNp6cxhhOetltlZMaXz5eBZNuEQSuNNmwDAwCTd1+x9Kq17vvbiywzKSAm+oM5UDWGC3Zll5+nQZ8NmDJtXYmJTid0UyeaRz5mU9S3HxXKOymjg8jBOdYW8pIPf2ELV72tLCDw=,iv:uMGUkLPtO6C3FHvVLsNH9miG8exqjFlcjzstWXnPN04=,tag:U7+sbShpHpB70KqWd8fFKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
