apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-db
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 2Gi
