apiVersion: v1
kind: Secret
metadata:
    name: ksops-smoke
type: Opaque
stringData:
    hello: ENC[AES256_GCM,data:aQWsGtHCFw88vyj9610QBzGh,iv:BKEVbMDkwoA6seO/56tCnZF5na6eyNwOq5lk99Kylq4=,tag:adZyyYtgmUOeD1fGI3HZuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR2hacktOdWoyKzhSeTh3
            MHVpdUpreUxqWDByRytsVFZ6RXBwbEQ5WHdzCnBjVUhpZjE3NERDdnhHckN0TDFi
            dmNOeU9Ybm1CM20yMURSdHRwS25LUlEKLS0tIHByUDRqeE9lUlkvc0pab3pZQVVE
            cGU4L1hPeHNNYkd3eDVkNWZWdGdaWVkKmZuEjws3TsHRkfaFgfhk3nbUeXVDmr7A
            LxARHGFP/7yXOL+16J2s1VLg5XSF/x/NjHg6w+lNEcUEOXFujL7z9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T08:44:12Z"
    mac: ENC[AES256_GCM,data:KGgVjba5bb6uXMtA0oBPQO3qOSBWJNo5ILBBO7Ahuqh0qgd5mwKzXRc50w8nKysCAH+YgApxd/xMyo8jLkDR/MpZXU5nIue/Z6a8osSeisHdNId0DJqJawLuZjVcEaCvEGwnr6GMdwzmaUN52Jjfv+hRRNJQGS8B5o/fBkUa9bc=,iv:gNJk42q2iZgHpQEWUBUd2phJpvBBBOPRpu9yiT8x45M=,tag:oavUqomKTWpcgopTcCRjUg==,type:str]
    version: 3.13.3
