apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:sdiuKI5dk4mBiLZo7mjBcc63XVZrKPn/3wINWSaDhtyAzFqSL6ERfeKOtVK+Oi15a2jAzpZuoRFnuvN3XqgPnkxYJZ0KJ8uIs65rM2NleVs=,iv:Za4XgZTynuUlFvp47oDb4nOk0w3MVmz0q4fyi/pAgYg=,tag:Ms01JdgO2svs0AJctNzHqg==,type:str]
    bootstrap-email: ENC[AES256_GCM,data:6uFZNux9z9bBodLhdmt9sbBu,iv:7sa7JT2we55VuDAjwS+HGpw0hz9H1B4arFuM1GO0s/g=,tag:2VTBcCawGv5gaG/eP83H4g==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:91hrldDOTjJUVVrdc1EqBAYmrxuzMSTt40gDWy/eTCE=,iv:RJlyq5aw/vWs+qDq/NnLrOJ5iQdFPNBLy4DgqzUe3OE=,tag:wSa7lbFNR87HNXZ7iL9YmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WkVlc1djQ2lvb2luaTRm
            WXAvLzNYcGNoMjRQUnBhZXIwalBsTzE1M2dVCjJDV0hwNGhOUFZJMUZ5TWFFM0ZX
            a21Qc1gydjVwaWgwZHl2OHBxb3JudjgKLS0tIENwLzFVdnVlWWJsR2NsZzFDZW5s
            NmRKL2JUaWwrcFdaWVoyT1JFNTd6TlEKINT1ZuV8VrWzm4YH7H45OWnqtiOK7Fio
            1sLdC00jUjKaQ+IFewz8dzBiTXMILRl2ikNcGaS0MVYPvWNlsnW9zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T11:44:36Z"
    mac: ENC[AES256_GCM,data:3LMOXiTFJfv3UOtPBB4lPtIJUqPZ5qLGfPPpwXC4IK6dup4xRnjHcmtrpL7qy5U4nLQMRQJ/8/zIvzBB/cFpjQgW6z/Rpo444Aeuh0MMQDE1Uoj/WXSsakwY0RgRc+EyI6MSjeQEE+DFF5sbeKr9lLOVIgvdT5//lz3QW/msO1Q=,iv:IDGHSHDbMJ6EvzqHiHlJ+MiL9hMCXuf1403Qrlu5j0k=,tag:U8f42s36JX4lfGov2oqUBw==,type:str]
    version: 3.13.3
