apiVersion: v1
kind: Secret
metadata:
    name: immich-config
    namespace: immich
type: Opaque
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:WxCTVAO1km65EBVck7D9bE3XV8mRqX5bhytbo/Ax45BZDYLYO52e+L5bVZrcY2TKkbL2WZEdDKzpsXctCFTNhYEXgPEbBaaWhqy8Ad95kgaIV9eu5iy9h7L55RGbWjdepYKnBlXodmSV6VsUmU/k+pghFhV5BfttanuDsu+hHusDJqlKxHcY1Huhd9k4I9gEDZ9pxQb+mUsSNdi2Gkz+J+EEa+beDdFVTLdY+SwghEAxot1G+ObNeKRTe4eN8vV7AQGEcjkJRPA39YnxR2nGhRB+MsVttSE+mVxav2M0o/ZDquObpLVcVHNbl7VZOeJc2B0QcwTOCe+S1TT+OLKPFXEX6aolGZLon0uNk1SPsGMXd9cV6EmDfNgNbvfiYVBJukO0URK3zx4RyLQ6HUZDiRAqo6bVPEj9py1o/9KYrQCVGbDoHMoqGTdQRvljmEIoTGlXTBSk8+TfaXE4EHnK12+noELuQgxrI0aAroqHODEFS83Q9pLJXytv3A3N5SXVM23+palfhQPtB2bMSTWtIC9wTw8n8e80ZX3fqiCzlu6C1RhEoOIVGEu0zh6M2gyCFQWWNvgoqpmXNiFc2K60jmwAR1cE2u3hPoBQ5BEuBLcnQm0mUSFMAl7c5/xFWSmtoBl86DHokUI5lUCOa4WE314bJJ5Ccm5Cid5gL/DjX9lbg1fvbZNMId+GQKG9bxBiNMiTBCe7llKS6q5zC524sp3HOxTaBC5AhYRE/MY9Ar4mNqsFGpjV7GvZP56Rbs7xFgIBj4o0p0geRkanamxPibdbCuankc9FZLzeq6XqL+dT8wB2ihmJww2P/mkQYaMpFcAla7cpEzKHUUeZSEpaTjkPjWw7xic4tcVrCc3xCUe3opGQpH8ehBEMGMzvSraosaZnYYEbxUgtUT4=,iv:K1qNJ8vix02qyrz8PEOsvBnU83Vh3E/oo5IaqA61OZQ=,tag:57b5GK/Bpr8/VlvO4SiB2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMUpIQlM5Q01qMjlURTlu
            OXJSa2FHSzJxcXNhSzArRUd6dTNoS0wwVlYwCmFYL0hjVUNhMjhCVnhXVVd0djVB
            RlRKTmN4K1NvNWREbGFYRk1XZnE2QncKLS0tIElCTW9xd0QxTlVjRkkxYXp1STJM
            ZXZvN0NQalZOMitKNXRlTzc2NEZOTkUKTQ5pP9qRA8IV1D1wuT5PWyXkMY8grRDn
            Jkp6TH57RHZ0nTcU4G/OhP9wpDUq4XJc9yx2XXQ2dv21UwcQVqtsOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T12:42:29Z"
    mac: ENC[AES256_GCM,data:TGAFNkaZl7xPPTEJb0BQkNwW6rxg6ZdnHLHBVkEj+JcJrUdzvHGHdU6+i56LPyihCCWviCR1ickUgafoJ3EMli+fsYO3fx+ABEsKnUYWbJ3PdggFaLJlvwucOT9YrHihaAzvhVwQ+C9I3ZhZsIZ8Ytw4fAS5k0gENARy3M3D/5s=,iv:ocnLO63P71HDREjxZU4Gn2HFdGMlNRU05uOeBtEynsw=,tag:9P7m5SsgBfZdD34zMjO49Q==,type:str]
    version: 3.13.3
