apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:6c0COX8xQJyoVj5+xgabN0kb73lStDk6M6szLAyE518XxpIgg/WjCXwj0cCixgRYmtGWZCkorwGiwSQpHz4konphRDxq60wS2aFXjXTxP/iBIbmIdgq0y8EJVPGBPnqfNSHayROs6hRy37Q/j2AwzexS4Z4zbqpF4mwN4l2rY8OZsm5KsAlwW+uf5mjc79rFdMestyIqK/EFizqHXfT99PA/N+tVabG46pEwtVRUN81DfwVTL10ndTmIrlLJ88e5+1eC,iv:H7deqTmk/WKGwGSp3Mb2k56Gei+eVyFGwnnbT5KhrCM=,tag:icKijrBVavSf7cp3C0pU5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NHdoRGRWUWQ1SlpGQlEz
            dE1McXg3ck9ZanNGRVRTRG1relJiY3BHR1RVCkdpaEJTOFdVL1EzSmtwMjVabVVl
            UXFNUnJXM1A5TTZ0NzliVWU2OFVxcUkKLS0tIEtCL2lsb1hZaWxZWUVya24xSE1M
            VlFiN1JpaTdHRjNTRkptZEVnQVlqRmMK398s6xuzyETbfj5dIED4F7jmPWN2kC33
            1dwZkAxGZ0efgRqUCcUYSi97cd+IseOQ5gUvplku7TLIojhAUF5JMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q53shld6cugy5y4c7d4n2ltlc03zpz9shuuqr5tqgzkr8v40ta4qnaj44q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T09:38:05Z"
    mac: ENC[AES256_GCM,data:xkCPMh7XC4KWxKyOdEnVrE3yOGkqLJtbV6uR9ke2HkOJ6krv7eqNGWL01UMIb48gfX7utI1fn6ZztqltZ0LMz8DJZgwb0qwmNDLax8W66e2exBomzGjkFqfTl0zPb/xZHxeoEwUuyxKlVeb6M2eMywIU3brUAanBryjZ5mkM7gE=,iv:aV89nE2bsQeuqDyFXI+lJMEpp+MnLTy8uUXGtqxarc4=,tag:9TkY5TdMFQ+PJxkEViAUwQ==,type:str]
    version: 3.13.3
